title: Bootdev Notes
description: My personal notes on various topics.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
